title = 'The Rust word Finder development plan'
file_name = 'Rust-Word-finder-beginning'
description = 'The purpose of article is for me'
tags = ['purpose']
posted = '14/01/2022'
estimated_reading_time = 1
author = 'Kevin Park' 
order = 1
